version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... zipping my webpage"

  post_build:
    commands:
    - echo "Deployed to s3"

artifacts:
  files:
    commands:
    - cp s3://webs-artifact/cicd-pipeline/BuildArtif/* s3://webs-Destination/*` 
